apiVersion: apiextensions.crossplane.io/v2alpha1
kind: CompositeResourceDefinition
metadata:
  name: privatebuckets.demo.crossplane.io
spec:
  scope: Namespaced
  group: demo.crossplane.io
  names:
    kind: PrivateBucket
    plural: privatebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            providerConfigName:
              type: string
              description: ProviderConfig to use to provision resources
              default: default
            region:
              type: string
              description: Region where the resources will be created
              default: us-west-2


