apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  generateName: crossplane-bucket-
  labels:
    demo.crossplane.io/scenario: legacy-refs-bucket
spec:
  forProvider:
    region: us-west-1